---
version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: events
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: events
